# Generated by Django 5.2.4 on 2025-07-22 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("company", "Company"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=20)),
                ("apartment", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("nip", models.CharField(max_length=10)),
                ("regon", models.CharField(blank=True, max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clients_company_name", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(blank=True, max_length=100)),
                ("nip", models.CharField(blank=True, max_length=20)),
                ("regon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="backend.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="backend.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="backend.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("description", models.TextField()),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("pcs", "Sztuki"),
                            ("h", "Godziny"),
                            ("kg", "Kilogramy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="backend.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "net_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("net_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gross_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="backend.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.product",
                    ),
                ),
            ],
        ),
    ]
